In [1]:
import pandas as pd

In [29]:
df = pd.read_csv('us_mexico_border.csv')
df

,Port Name,State,Port Code,Border,Date,Measure,Value,Latitude,Longitude,Point
0,Roma,Texas,2310,US-Mexico Border,Dec 2023,Buses,46,26.404,-99.019,POINT (-99.018981 26.403928)
1,Del Rio,Texas,2302,US-Mexico Border,Dec 2023,Trucks,6552,29.327,-100.928,POINT (-100.927612 29.326784)
2,Roma,Texas,2310,US-Mexico Border,Nov 2023,Trucks,3753,26.404,-99.019,POINT (-99.018981 26.403928)
3,Douglas,Arizona,2601,US-Mexico Border,Oct 2023,Buses,13,31.334,-109.560,POINT (-109.560344 31.334043)
4,Laredo,Texas,2304,US-Mexico Border,Aug 2023,Buses,2843,27.500,-99.507,POINT (-99.507412 27.499561)
...,...,...,...,...,...,...,...,...,...,...
92080,Rio Grande City,Texas,2307,US-Mexico Border,Mar 2024,Personal Vehicle Passengers,86145,26.366,-98.803,POINT (-98.802513 26.365761)
92081,El Paso,Texas,2402,US-Mexico Border,Mar 2024,Rail Containers Empty,9247,31.764,-106.451,POINT (-106.451188 31.764363)
92082,Santa Teresa,New Mexico,2408,US-Mexico Border,Mar 2024,Bus Passengers,1096,31.784,-106.679,POINT (-106.679437 31.783939)
92083,Lukeville,Arizona,2602,US-Mexico Border,Mar 2024,Trucks,70,31.880,-112.817,POINT (-112.817077 31.880195)
92084,Calexico East,California,2507,US-Mexico Border,Mar 2024,Pedestrians,56301,32.673,-115.388,POINT (-115.388018 32.673389)

In [33]:
df['Date'] = pd.to_datetime(df['Date'], format='%b %Y')
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

# Drop the original 'Date' column if no longer needed
df = df.drop(columns=['Date'])
descriptive_stats = df.groupby(['Port Name', 'Year']).describe()
descriptive_stats['Value']

                count           mean            std      min       25%  \
Port Name Year
Andrade   1996  144.0   24665.138889   51965.628986      0.0      0.00
          1997  144.0   24815.618056   52369.968817      0.0      0.00
          1998  144.0   26196.361111   54733.126866      0.0      0.00
          1999  144.0   28312.611111   59002.292453      0.0      0.00
          2000  144.0   29057.652778   61421.454398      0.0      0.00
...               ...            ...            ...      ...       ...
Ysleta    2020   55.0   95212.472727   89879.536630  10622.0  29446.00
          2021   76.0  117211.236842  116056.007083      1.0  33951.50
          2022   72.0  155684.222222  156598.106002  14828.0  35347.00
          2023   71.0  174324.084507  178436.372916  11285.0  39108.50
          2024   18.0  179046.277778  179205.771026  18848.0  54339.25

                    50%        75%       max
Port Name Year
Andrade   1996     96.0    9430.25  250598.0
          1997     72.5    9816.00  257453.0
          1998     76.0   10268.50  245425.0
          1999     65.0   11381.75  274920.0
          2000     34.5   11273.00  310134.0
...                 ...        ...       ...
Ysleta    2020  54839.0  155582.50  413216.0
          2021  57833.5  204908.75  423616.0
          2022  81700.5  267355.75  518286.0
          2023  75671.0  292542.50  572703.0
          2024  93808.5  299395.75  524319.0

[748 rows x 8 columns]

In [35]:
total_avgs = df.groupby('Year').describe()
total_avgs['Value']

,count,mean,std,min,25%,50%,75%,max
Year,,,,,,,,
1996,3600.0,76875.402222,294052.170832,0.0,0.00,303.0,10905.75,3797399.0
1997,3600.0,96850.413333,349508.367933,0.0,0.00,432.5,19252.50,3935404.0
1998,3600.0,101749.059444,359122.408271,0.0,0.00,460.0,20578.50,3913588.0
1999,3600.0,108877.610000,380420.932325,0.0,0.00,573.0,23409.00,4099560.0
2000,3600.0,108953.296944,376851.091397,0.0,0.00,594.0,24274.25,4291774.0
2001,3600.0,100830.975278,341751.781678,0.0,0.00,581.5,24419.75,4447374.0
2002,3600.0,98019.478611,308107.215818,0.0,0.00,558.0,27398.00,3357246.0
2003,3600.0,95459.510833,311763.581953,0.0,0.00,532.0,25173.00,3755585.0
2004,3600.0,95423.521111,302287.284453,0.0,0.00,543.0,25583.00,3119562.0
2005,3600.0,93608.490833,297732.527525,0.0,0.00,614.5,25254.50,3000768.0
2006,3600.0,90996.673889,289532.817758,0.0,0.00,700.5,25254.75,3181791.0
2007,3600.0,86137.709444,263670.506347,0.0,0.00,741.5,27038.50,2739652.0
2008,3600.0,82200.341667,249736.320126,0.0,0.00,685.5,26656.75,2460515.0
2009,3600.0,73458.401389,221573.451649,0.0,0.00,545.0,23813.00,2244432.0
2010,3600.0,67438.026111,207540.625811,0.0,0.00,545.0,24181.00,2088792.0
2011,3600.0,62650.302500,187296.349018,0.0,0.00,567.5,24004.25,1891804.0
2012,3600.0,64722.128889,188258.645762,0.0,0.00,576.0,25351.50,1775986.0
2013,3600.0,67772.840833,197811.090791,0.0,0.00,552.5,25410.00,1813172.0
2014,3600.0,70762.854722,209417.899648,0.0,0.00,619.5,25729.75,2193520.0
2015,3744.0,71491.302350,223380.914535,0.0,0.00,370.5,22469.00,2269563.0
2016,3179.0,86043.537276,240936.365695,0.0,0.00,2020.0,36507.00,2138861.0
2017,2331.0,119563.707422,279758.793955,0.0,778.00,10011.0,73383.50,2164841.0
2018,2313.0,122673.236922,286179.297110,1.0,877.00,12386.0,82042.00,2245201.0
2019,2321.0,118715.271435,273533.090560,1.0,871.00,12344.0,84741.00,2470347.0
2020,2296.0,74488.100174,179559.868031,0.0,957.25,9414.5,59513.50,2298003.0
2021,2299.0,86795.154415,202912.057262,0.0,1350.50,12595.0,71193.00,2049773.0
2022,2299.0,110957.850805,245398.529561,1.0,1238.50,14378.0,92325.00,2230225.0
2023,2328.0,115913.170533,252724.544568,1.0,1143.75,15037.5,94342.00,2302112.0
2024,575.0,116343.678261,241415.498782,2.0,1134.00,16337.0,100441.00,2015086.0

In [38]:
state_avgs = df.groupby(['State', 'Year']).describe()
state_avgs['Value']

               count           mean            std   min      25%      50%  \
State   Year
Arizona 1996   864.0   44026.619213  130715.221156   0.0     0.00    151.5
        1997   864.0   46886.991898  137258.996058   0.0     0.00    198.5
        1998   864.0   47964.496528  141821.160601   0.0     0.00    243.0
        1999   864.0   51284.406250  149501.099486   0.0     0.00    300.0
        2000   864.0   53767.810185  158829.877579   0.0     0.00    299.5
...              ...            ...            ...   ...      ...      ...
Texas   2020  1137.0   67418.817062  136413.357933   1.0  1730.00  14006.0
        2021  1153.0   78336.170859  146171.468470   1.0  2295.00  14818.0
        2022  1132.0  105361.891343  201580.291200   8.0  2699.25  15808.0
        2023  1160.0  110523.365517  208213.191168   1.0  2440.50  16943.0
        2024   292.0  112794.667808  202438.129360  46.0  2491.50  18463.5

                    75%        max
State   Year
Arizona 1996    4712.00   840953.0
        1997    5129.50   892381.0
        1998    5368.75   850421.0
        1999    5392.75  1268880.0
        2000    7391.75  1306680.0
...                 ...        ...
Texas   2020   61515.00  1593590.0
        2021   77518.00  1148477.0
        2022  105141.75  1275644.0
        2023  115195.50  1256754.0
        2024  117828.50  1064426.0

[116 rows x 8 columns]